import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from "./_components/layouts/Header/Header";

import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const alibaba = localFont({
  src: [
    {
      path: "../../public/fonts/alibaba-regular.woff2-5d2979c4.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/alibaba-bold.woff2-bbb24413.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/alibaba-black.woff2-41970917.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  // variable: "--font-alibaba",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        suppressHydrationWarning={true}
        className={`${alibaba.className} antialiased`}
      >
        <NextTopLoader showSpinner={false} color="#fdb713" />
        <Header />

        {children}
      </body>
    </html>
  );
}
